### PR TITLE
One session per context

### PR DESCRIPTION
**Pull request by sdether**
Removed the concept of local session inside execute and instead lazy initialize a single CassandraSession per CassandraContext

### CODE REVIEW

**Comment by nberardi** [comment]
The big question is why is this nessisay? Isn't this just managed by the connection provider?

In the case of a pooled connection the connection pool keeps the connection open until it times out. So keeping he session around for longer doesn't really matter. And it is almost free to setup a new session. 

In the case of a non-pooled connection the developer always has the option to pass in his own session, which is more declarative and allows for greater control. 

But taking this code at face value ignoring the concerns raised above. What happens to this code if the context sticks around longer than the session? The server or OS could choose to kill the underlying socket at anytime.

**Comment by ilushka85** [comment]
We are seeing connection time out waiting on pool... here is what we have done:

```
public InfrastructureDataStorageMapperBase()
    {
        var builder = new ConnectionBuilder(ConfigurationManager.AppSettings["InfrastructureDataConnectionString"]);
        db = new CassandraContext(builder);
    }
```

basically all our classes call this method and they also call dispose on the db object at the end and our connections get messed up.

**Comment by ilushka85** [comment]
should we do this instead?

 var builder = new ConnectionBuilder(ConfigurationManager.AppSettings["InfrastructureDataConnectionString"]);
            CassandraSession cs = new CassandraSession(builder);
            db = new CassandraContext(cs);

**Comment by sdether** [comment]
@nberardi Generally sockets don't get killed unless something went wrong. I mean if you have a SqlConnection and the socket gets killed your transaction is void, so the context should die as well. Now Cassandra being non-transactional, that's not a concern, but still a socket getting closed on you is a sign of a problem and should bubble up, imho.

If you do stay with a session per execution, and tune the pool for better concurrent performance instead, you still have the problem that iterators would have to be changed to prevent their captured session from being disposed. That seems like it's a lot more fraught with edge cases than just avoiding it and using a single session.

Since i can provide my own session to the context (although i have to then manually dispose it as well), I can certainly work with the way the library is right now, I just don't see the benefit considering the added complication in the underlying moving parts. I think from the perspective of user expectations a failed socket making the context fail seems more intuitive than bottlenecks in performance and brittle iterators because of opaque connection handling.

**Comment by sdether** [comment]
@ilushka85 if you want to use a session per context with the current code you'll want to do this:

``` csharp
var builder = new ConnectionBuilder(ConfigurationManager.AppSettings["InfrastructureDataConnectionString"]);
using(var cs = new CassandraSession(builder)) {
  using(var db = new CassandraContext(cs)) {
     .. do work
  }
}
```

I.e. once you take the responsibility for creating the session, you also must take responsibility for disposing it.

**Comment by nberardi** [comment]
> > once you take the responsibility for creating the session, you also must take responsibility for disposing it.
> > Merge pull request

same goes for the CassandraContext.  With your method the user still needs to take responsibility for disposing of the context.  Either way the responsibility is still there.  

There is also a reason that it is setup like it is. Over the past two years I have consistently had programmers programming against the context like this. (this just came up this morning by the way)

https://groups.google.com/forum/?fromgroups=#!topic/fluentcassandra/kOa_bZXmd5o

I am not saying that having one context per many threads is correct.  But I have seen it enough where developers have been doing this.  And if I was to include your change into the source code all their apps that are currently working would break, when they update the library.

If you want to find another way to do this I am happy to accept the change, but I cannot change any default functionality, when it may effect other programs.  Major financial institutions are using this library for their own proprietary needs, so I have to approach any change that changes default functionality with caution.

**Comment by sdether** [comment]
Per the recent discussion on https://github.com/managedfusion/fluentcassandra/issues/29, i withdraw the pull request, as my presumptions about CassandraContext longevitity in light of socket lifespan is wrong. I'll just manually create the session until the performance issues of the pool are addressed.

Also, my condolences on the bugs of DbContext being shared across threads. Ick. I don't know about EntityFramework, by NHibernate is very explicit that a Session cannot be used on multiple threads. I was going to suggest pinning the context to a thread, but with async/await you can be single threaded and still not stay on the same thread you started on, so that's not safe either.

**Comment by sdether** [comment]
I started digging into `CassandraSession` and noticed that it already does most of the equivalent of EF's `EnsureConnection`, since every `Execute` that it facilitates goes a `GetClient`. So `CassandraSession` already isn't tied to a single connection. It does however currently throw if the underlying connection was disposed, which could easily try to to get a fresh connection instead like this:

``` csharp
try
{
    if (!_connection.IsOpen)
    _connection.Open();
} 
catch(ObjectDisposedException)
{
    _connection = ConnectionProvider.Open();
    if(!_connection.IsOpen)
        _connection.Open();
}
```

With that change, I would say that having the single `CassandraSession` per `CassandraContext`, where the lifespan of the `CassandraSession` created internally would be the governed by the lifespan of the owning `CassandraContext`, would be a sensible approach. Since the concept of a per execution location session is already invisible to `CassandraContext` users, this change would not be perceivable by any existing users. Rather it would reduce lock contention and solve your iterator problems.

Can you think of a reason why this wouldn't be a transparent improvement or introduce a new form of risk? If not, I would like to re-submit this pull with the `GetClient` change.

**Comment by nberardi** [comment]
> So CassandraSession already isn't tied to a single connection.

It is tied to a single connection, because nothing sets it to null after a connection has been retrieved.

https://github.com/managedfusion/fluentcassandra/blob/master/src/CassandraSession.cs#L102

This is by design so that the Session can be used across contexts and multiple calls to the database.  I know you don't agree with it, but I cannot change it.  These paradigms are well ingrained and if I start messing around with how connections happen this could have serious effects on peoples applications. I know a ton of people are using the library like this developer, and your change would break all their applications.

https://groups.google.com/forum/?fromgroups=#!topic/fluentcassandra/kOa_bZXmd5o

Maybe we should start talking a little about why you feel passing in a session to maintain a longer connection is a burden to the user?  Because here is how I do it.

``` csharp
using(var session = new CassandraSession("Testing", "localhost"))
using(var db = new CassandraContext(session)) {
    // do work
}
```

By default I developed CassandraContext to be safe, so that it always connects to a database and the user didn't have to worry about if the connection was closed previously or other socket issues that may happen. This was very nessisary in the early days of Cassandra (pre 0.7), because it would randomly close open connections if no work was being don. This doesn't mean this is the most performant way to use CassandraContext but it is the safest way to use CassandraContext.  Especially in multi-threading scenarios.

**Comment by sdether** [comment]
Honestly, I really don't know why I am tilting at this windmill. I don't like that the default behavior given a ConnectionBuilder is to create and dispose sessions over and over, but my liking it is neither here nor there. Given that sentiment, however, I thought I could change CassandraSession to re-create its connection in case of failure/disposal. I figured have it would be a transparent change that would make things more efficient for everyone, but you are correct, that would be an observable change in behavior that could cause problems with existing users and code.

So i'm just going to go with the managing my own session for the context.

**Comment by nberardi** [comment]
I would consider configuration modifications to allow this to function how
you want, but the default behavior cannot change. And I don't really know
if a session provider makes things any easier or just adds another layer of
complication.

**Pull request closed without merging**
