### PR TITLE
added the ability to delete a column value in a FluentColumnFamily

### PR DESCRIPTION
**Pull request by gillotte**
nberardi, Not sure how to contact you, can you shoot me an email at gillotte@gmail.com ?

I've been working with fluent cassandra a bit the and I would like to sync up on the direction of the project and stuff.

Thanks,

### CODE REVIEW

**Comment by nberardi** [comment]
Thanks for the commit, but there is already a method in FluentColumnFamily which is called RemoveColumn.  (this method comes from the shared FluentRecord object)

https://github.com/managedfusion/fluentcassandra/blob/master/src/FluentRecord.cs#L173

Does this method not work for you, or were you unaware of it?

**Comment by gillotte** [comment]
Remove in FluentRecord doesn't actually trigger a mutate of the object it only changes the collection. 

I implemented delete in FluentColumnFamily because it needs to be able to set the 'parent' of the column which gives the col ref to the row key. So it couldnt be implmented in FluentRecord because  getself in col.SetParent(GetSelf()); is out of scope

**Comment by nberardi** [comment]
It should add a mutation. It is part of the custom collection class.

## 

Nick Berardi
(484) 302-0125
Sent on the go from my phone.

On Sep 9, 2012, at 3:43 PM, gillotte notifications@github.com wrote:

Remove in FluentRecord doesn't actually trigger a mutate the object it only
changes the collection.

I implemented delete in FluentColumnFamily because it needs to be able to
set the 'parent' of the column which gives the col ref to the row key. So
it couldnt be implmented in FluentRecord because getself in
col.SetParent(GetSelf()); is out of scope

—
Reply to this email directly or view it on
GitHubhttps://github.com/managedfusion/fluentcassandra/pull/62#issuecomment-8408409.

**Comment by gillotte** [comment]
I see, so the problem for me is that Remove will not let you delete a column unless you just fetched that column from the database. 

If you create a new record object, attach it, and do a remove the column it wont trigger the mutate because it cannot find the column. 

This is how I found it, when I saw remove came from ICollection I assumed it was just a from a derived list type or something.

At any rate you should still be able to delete a column without downloading it first.

**Comment by nberardi** [comment]
There is a way to delete a column that you haven't pulled. Get the column
family from the context. And call RemoveColumn from there.

https://github.com/managedfusion/fluentcassandra/blob/master/src/CassandraColumnFamilyOperations.cs#L93

It doesn't do a mutation, but that is the recommended way.

## 

Nick Berardi
(484) 302-0125
Sent on the go from my phone.

On Sep 9, 2012, at 4:31 PM, gillotte notifications@github.com wrote:

I see, so the problem for me is that Remove will not let you delete a
column unless you just fetched that column from the database.

If you create a new record object, attach it, and do a remove the column it
wont trigger the mutate because it cannot find the column.

This is how I found it, when I saw remove came from ICollection I assumed
it was just a from a derived list type or something.

At any rate you should still be able to delete a column without downloading
it first.

—
Reply to this email directly or view it on
GitHubhttps://github.com/managedfusion/fluentcassandra/pull/62#issuecomment-8408969.

**Comment by gillotte** [comment]
Wouldn't doing mutations be the best approach? It would allow for batch updates on .SaveChanges() on the context

**Comment by nberardi** [comment]
I would however accept this pull request if this was moved to
FluentRecord and followed the TryGetColumn approach. And changed the
functionality of RemoveColumn to use TryRemoveColumn.

https://github.com/managedfusion/fluentcassandra/blob/master/src/FluentRecord.cs#L73

Also you should only create a new column to be removed if it is not already in the Columns collection. Because the remove should also remove it from there.

**Comment by gillotte** [comment]
Ok sounds good, I think I know what you mean

**Comment by nberardi** [comment]
Sounds good, so make TryRemoveColumn an abstract FluentRecord implemented
in FluentColumnFamily

Exactly

**Comment by gillotte** [comment]
Whatever FluentColumnFamily does it wont fail because if it is not in memory it will create the column to be deleted. So calling it TryRemove doesn't quite fit. So I swapped the names, so now TryRemove is implemented in FluentRecord because it is unware on how to create columns.

As for the FluentSuperColumn case, correct me if I'm wrong here, but you cannot manipulate the internal state of a super column, you can only replace it right?

**Comment by nberardi** [comment]
No you are wrong about FluentSuperColumn, They all work the same way from the mutations.  It just depends on the resolution you give it.  But you don't really have to worry about the resolution stuff as long as you just follow what has already been done for Get and Set.

Also what you are saying is inline with Get and Set for having RemoveColumn in the three instances FluentColumnFamily, FluentSuperColumnFamily, and FluentSuperColumn

**Pull request merged**
