### PR TITLE
CQL3 can return null for Long and Int32 typed columns.

### PR DESCRIPTION
**Pull request by edweip3**
added code to check for null in LongType and Int32Type

### CODE REVIEW

**Comment by nberardi** [comment]
Can you please fix the spacing.  And are you sure that the byte value comes through as null instead of zero bytes?

**Comment by edweip3** [comment]
sure.. i will fix the spacing.  and yes, it's null instead of zero bytes.

**Comment by nberardi** [comment]
Also I don't think this is the right place for the code.  This can essentially happen to any of the types, so please move this code to here:

https://github.com/managedfusion/fluentcassandra/blob/master/src/Types/CassandraObjectConverter.cs#L53

``` csharp
if (value == null)
    return default(T);
```

That should fix this problem for all types.

**Comment by edweip3** [comment]
ok.. i will resubmit a pull request.

**Comment by nberardi** [comment]
You don't have to resubmit, you just have to keep contributing, the changes will show up automatically.

**Comment by nberardi** [comment]
But the damage has already been done, you closed it so it cannot be used any longer.

**Pull request closed without merging**
