### PR TITLE
Blacklisting enhancements

### PR DESCRIPTION
**Pull request by eplowe**
Ability to reclaim a server that has been blacklisted due to connection error, etc etc. Also the ability to retry an operation if an exception is thrown based on the type of exception thrown calls for a retry attempt up to a user defined number of retries which can be defined in the ConnectionString or ConnectionBuilder.

### CODE REVIEW

**Comment by nberardi** [comment]
I don't understand why the IsHealthy stuff is in `CassandraException`?  How does this relate to type errors that never even touch the server?

**Comment by tjake** [comment]
How long should it take for a server to be un-blacklisted? assuming it was restarted and back up quickly

**Comment by eplowe** [comment]
Nevermind I see my changes there.

**Comment by tjake** [comment]
I'm trying to test this by restarting cassandra and waiting for the retry to not error but it never seems to work

**Comment by tjake** [comment]
Here is my connection string:

&lt;add key="CassandraServers" value="Keyspace=dev;Server=CASSANDRA05,CASSANDRA06,NYCASSANDRA07;Pooling=True;Max Pool Size=1024;Connection Timeout=120;Connection Lifetime=120;CQL Version=3.0.0;Compress CQL Queries=Yes;Max Retries=3" /&gt;

**Comment by eplowe** [comment]
I am using a connectionstring with 6 servers, if I take them all down but one --- I am am still executing, if I bring them back up i am seeing them leave the blacklist. post a code example with more than the connection string.

**Comment by tjake** [comment]
Maybe the diff is I am taking them all down?

**Comment by eplowe** [comment]
Well if you take them all down you'll get a major exception as there are no
more servers to return.

**Comment by tjake** [comment]
But once I bring them back they should reconnect no?
My code is just query, catch exception,  sleep tryagain

**Comment by eplowe** [comment]
Yes

**Comment by nberardi** [comment]
I re-factored your code a little, I wasn't thrilled with using exceptions to pass state data.  But over all it was a good addition, thanks for commiting it.

**Comment by nberardi** [comment]
I opted for a simpler black list checker that runs every 30 seconds. As we
better understand the code we can tweak this or make it configurable.

## 

Nick Berardi
(484) 302-0125
Sent from my tablet.

On Nov 20, 2012, at 5:06 PM, Eric Plowe notifications@github.com wrote:

please reject my previous pull request so I can send a new one.
Blacklisting checks right now every 5 seconds from the time a server
becomes blacklisted. I also moved IsHealthy/ShouldRetry to
casandraoperationexception

On Tue, Nov 20, 2012 at 4:46 PM, Jake Luciani notifications@github.comwrote:

> How long should it take for a server to be un-blacklisted? assuming it
> was
> restarted and back up quickly
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/managedfusion/fluentcassandra/pull/88#issuecomment-10574604>.

—
Reply to this email directly or view it on
GitHubhttps://github.com/managedfusion/fluentcassandra/pull/88#issuecomment-10575709.

**Comment by eplowe** [comment]
It was an attempt to determine based on the exception given for an
operation if that deemed the client was healthy and if we should retry --
that was all. That why we can use the error to determine what to do. that
was all.

**Pull request merged**
