### PR TITLE
Fixes for broken unit tests issue #107

### PR DESCRIPTION
**Pull request by Aaronontheweb**
We were able to isolate the issue to the TimeUUID tests - the fixes applied to the attached commits enable 50+ more unit tests to pass than were passing previously.
#107

### CODE REVIEW

**Comment by caglarmarkedup** [comment]
Basically all the test fails right after the Save_DateTime_Local test. This test basically poisons the connection for the other tests which make them fail. The issue is I think on the conversion of the DateTime, somehow it gets screwed up when you convert them to the byte level. The creation of the column goes fine but on the read request it dies out because cassandra can't return the correct value. Please do look at Cassandra.cs Line 631 and following function recv_get() at this point Cassandra returns an exception. These are the values that get added to the DB. 
Row Key     Columns

Test1   2010-11-20 08:00:00 UTC: @\x09!\xfbTD-\x18

**Comment by nberardi** [comment]
This doesn't really fix the test. You changed the test so it would break anymore. There is still a casting issue tat needs to be resolved.

**Comment by nberardi** [comment]
@caglarmarkddup Cassandra.cs is generated by thrift so we can't touch it. Often it looks like issues are coming from here because this is where exceptions get thrown from. But it throws exceptions on Cassandra's direction. So the issue must be somewhere else. 

Also make sure you set Cassandra up using Java 6. Java 7 breaks Cassandra and thus breaks the tests.

**Comment by Aaronontheweb** [comment]
@nberardi so what exactly is the casting issue? We could tell that there was a problem and we followed it all the way through but it wasn't clear what the underlying problem was.

On top of that commit 18e36e2bdaa499f50429fffbec21aebe24dfbfc8 fixes a typo in DatabaseSetup.cs which would cause the test fixture to break.

**Comment by nberardi** [comment]
Typically an issue like you are seeing would boil down to this class.

https://github.com/managedfusion/fluentcassandra/blob/master/src/Types/TimeUUIDTypeConverter.cs

My guess is that since converting to GUID ahead of time works that it has something to do with the byte conversion.  Typically date issues boil down to one of two things, the resolution gets truncated and the .NET nano seconds don't match the millisecond resolution that Cassandra loves to use.  Or the correct DateTime.Kind isn't picked.  This is similar to the DateType issue that we discussed before.

**Comment by nberardi** [comment]
I should explain why I really didn't like these changes better.  They essentially just duplicate the `Save_Guid` test and not really test the ability to save date types.  So I would rather have these fixed or at the very worst marked as `Skip` instead of producing false positives.

**Comment by nberardi** [comment]
This is related to the `GuidGenerator` changes that were made a while back in issue #66 by @GrLawrence and @dlbromen and myself

06f40800-f463-11df- **9bd9** -12079974fbad

The 2 bytes that I highlighted are getting changed with each request, which makes it unusable because it is constantly regenerating new numbers when you pass in the same date.

**Comment by Aaronontheweb** [comment]
@nberardi makes sense to me - we just wanted the other tests to pass more than anything else; marking those tests as skip makes sense too.

**Comment by nberardi** [comment]
Well I fixed them, but that is just my preference.  A passing test is no use if it doesn't actual test what it was designed for.  IMO

**Comment by Aaronontheweb** [comment]
I totally agree with you - we hacked the test because we're adding
FluentCounterColumn support in batch mutations and needed the rest of the
CRUD fixtures to pass in order to give us some visibility into whether or
not our changes work.

On Fri, Jan 25, 2013 at 11:44 AM, Nick Berardi notifications@github.comwrote:

> Well I fixed them, but that is just my preference. A passing test is no
> use if it doesn't actual test what it was designed for. IMO
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/managedfusion/fluentcassandra/pull/108#issuecomment-12717417.

## 

Aaron Stannard,
Santa Monica, CA

**Comment by nberardi** [comment]
Either way we are down to about 23 tests and most of them have to do with CQL. You help is much appreciated.

**Pull request closed without merging**
